// <auto-generated />
using System;
using Echipa_de_fotbal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Echipa_de_fotbal.Migrations
{
    [DbContext(typeof(EchipaDeFotbalContext))]
    partial class EchipaDeFotbalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Echipa_de_fotbal.Models.Angajat", b =>
                {
                    b.Property<int>("IdAngajat")
                        .HasColumnType("integer")
                        .HasColumnName("idangajat");

                    b.Property<DateOnly?>("DataN")
                        .HasColumnType("date")
                        .HasColumnName("datan");

                    b.Property<string>("Functie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("functie");

                    b.Property<int?>("IdEchipa")
                        .HasColumnType("integer")
                        .HasColumnName("idechipa");

                    b.Property<string>("NivelStudii")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nivelstudii");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nume");

                    b.Property<string>("Prenume")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenume");

                    b.HasKey("IdAngajat")
                        .HasName("pk__angajat__e09dcaf423939225");

                    b.HasIndex("IdEchipa");

                    b.ToTable("angajat", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Campionat", b =>
                {
                    b.Property<int>("IdCampionat")
                        .HasColumnType("integer")
                        .HasColumnName("idcampionat");

                    b.Property<int?>("Divizie")
                        .HasColumnType("integer")
                        .HasColumnName("divizie");

                    b.Property<string>("NumeCampionat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numecampionat");

                    b.Property<string>("Tara")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tara");

                    b.HasKey("IdCampionat")
                        .HasName("pk__campiona__04f7e09ba4b2d059");

                    b.ToTable("campionat", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.ContractAngajat", b =>
                {
                    b.Property<int>("IdContractAngajat")
                        .HasColumnType("integer")
                        .HasColumnName("idcontractangajat");

                    b.Property<int?>("ClauzaReziliere")
                        .HasColumnType("integer")
                        .HasColumnName("clauzareziliere");

                    b.Property<DateOnly?>("DataExpirare")
                        .HasColumnType("date")
                        .HasColumnName("dataexpirare");

                    b.Property<DateOnly?>("DataSemnare")
                        .HasColumnType("date")
                        .HasColumnName("datasemnare");

                    b.Property<int?>("IdAngajat")
                        .HasColumnType("integer")
                        .HasColumnName("idangajat");

                    b.Property<int?>("IdEchipa")
                        .HasColumnType("integer")
                        .HasColumnName("idechipa");

                    b.Property<int?>("Salariu")
                        .HasColumnType("integer")
                        .HasColumnName("salariu");

                    b.HasKey("IdContractAngajat")
                        .HasName("pk__contract__764965f3dfeccec1");

                    b.HasIndex("IdAngajat");

                    b.HasIndex("IdEchipa");

                    b.ToTable("contractangajat", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.ContractJucator", b =>
                {
                    b.Property<int>("IdContractJucator")
                        .HasColumnType("integer")
                        .HasColumnName("idcontractjucator");

                    b.Property<int?>("ClauzaReziliere")
                        .HasColumnType("integer")
                        .HasColumnName("clauzareziliere");

                    b.Property<DateOnly?>("DataExpirare")
                        .HasColumnType("date")
                        .HasColumnName("dataexpirare");

                    b.Property<DateOnly?>("DataSemnare")
                        .HasColumnType("date")
                        .HasColumnName("datasemnare");

                    b.Property<int?>("IdEchipa")
                        .HasColumnType("integer")
                        .HasColumnName("idechipa");

                    b.Property<int?>("IdJucator")
                        .HasColumnType("integer")
                        .HasColumnName("idjucator");

                    b.Property<int?>("Salariu")
                        .HasColumnType("integer")
                        .HasColumnName("salariu");

                    b.HasKey("IdContractJucator")
                        .HasName("pk__contract__ca852c6a9536a9ea");

                    b.HasIndex("IdEchipa");

                    b.HasIndex("IdJucator");

                    b.ToTable("contractjucator", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Echipa", b =>
                {
                    b.Property<int>("IdEchipa")
                        .HasColumnType("integer")
                        .HasColumnName("idechipa");

                    b.Property<int?>("IdCampionat")
                        .HasColumnType("integer")
                        .HasColumnName("idcampionat");

                    b.Property<int?>("IdStadion")
                        .HasColumnType("integer")
                        .HasColumnName("idstadion");

                    b.Property<string>("NumeEchipa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numeechipa");

                    b.Property<string>("NumePatron")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numepatron");

                    b.HasKey("IdEchipa")
                        .HasName("pk__echipa__36339d8588df9471");

                    b.HasIndex("IdCampionat");

                    b.HasIndex("IdStadion");

                    b.HasIndex(new[] { "NumeEchipa" }, "nume_echipa")
                        .IsUnique();

                    b.ToTable("echipa", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Jucator", b =>
                {
                    b.Property<int>("IdJucator")
                        .HasColumnType("integer")
                        .HasColumnName("idjucator");

                    b.Property<DateOnly?>("DataN")
                        .HasColumnType("date")
                        .HasColumnName("datan");

                    b.Property<int?>("Greutate")
                        .HasColumnType("integer")
                        .HasColumnName("greutate");

                    b.Property<int?>("IdEchipa")
                        .HasColumnType("integer")
                        .HasColumnName("idechipa");

                    b.Property<int?>("Inaltime")
                        .HasColumnType("integer")
                        .HasColumnName("inaltime");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nume");

                    b.Property<string>("Pozitie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pozitie");

                    b.Property<string>("Prenume")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenume");

                    b.HasKey("IdJucator")
                        .HasName("pk__jucator__9ac77f77a590dc05");

                    b.HasIndex("IdEchipa");

                    b.ToTable("jucator", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Sponsor", b =>
                {
                    b.Property<int>("IdSponsor")
                        .HasColumnType("integer")
                        .HasColumnName("idsponsor");

                    b.Property<string>("NumeSponsor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numesponsor");

                    b.HasKey("IdSponsor")
                        .HasName("pk__sponsor__2d5a6d8b5471799c");

                    b.ToTable("sponsor", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.SponsorEchipa", b =>
                {
                    b.Property<int>("IdSponsor")
                        .HasColumnType("integer")
                        .HasColumnName("idsponsor");

                    b.Property<int>("IdEchipa")
                        .HasColumnType("integer")
                        .HasColumnName("idechipa");

                    b.Property<DateOnly?>("DataSemnare")
                        .HasColumnType("date")
                        .HasColumnName("datasemnare");

                    b.Property<int?>("DurataContract")
                        .HasColumnType("integer")
                        .HasColumnName("duratacontract");

                    b.Property<int?>("SumaOferita")
                        .HasColumnType("integer")
                        .HasColumnName("sumaoferita");

                    b.HasKey("IdSponsor", "IdEchipa")
                        .HasName("pk__sponsore__6e395453add7d5aa");

                    b.HasIndex("IdEchipa");

                    b.ToTable("sponsorechipa", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.SponsorJucator", b =>
                {
                    b.Property<int>("IdSponsor")
                        .HasColumnType("integer")
                        .HasColumnName("idsponsor");

                    b.Property<int>("IdJucator")
                        .HasColumnType("integer")
                        .HasColumnName("idjucator");

                    b.Property<DateOnly?>("DataSemnare")
                        .HasColumnType("date")
                        .HasColumnName("datasemnare");

                    b.Property<int?>("DurataContract")
                        .HasColumnType("integer")
                        .HasColumnName("duratacontract");

                    b.Property<int?>("SumaOferita")
                        .HasColumnType("integer")
                        .HasColumnName("sumaoferita");

                    b.HasKey("IdSponsor", "IdJucator")
                        .HasName("pk__sponsorj__44f61a7ca3df434a");

                    b.HasIndex("IdJucator");

                    b.ToTable("sponsorjucator", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Stadion", b =>
                {
                    b.Property<int>("IdStadion")
                        .HasColumnType("integer")
                        .HasColumnName("idstadion");

                    b.Property<int?>("Capacitate")
                        .HasColumnType("integer")
                        .HasColumnName("capacitate");

                    b.Property<string>("NumeStadion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numestadion");

                    b.Property<string>("Oras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("oras");

                    b.Property<string>("Strada")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strada");

                    b.HasKey("IdStadion")
                        .HasName("pk__stadion__5cb1dafc2dc3e3d4");

                    b.ToTable("stadion", "dbo");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Angajat", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Echipa", "IdEchipaNavigation")
                        .WithMany("Angajati")
                        .HasForeignKey("IdEchipa")
                        .HasConstraintName("fk__angajat__idechip__37a5467c");

                    b.Navigation("IdEchipaNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.ContractAngajat", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Angajat", "IdAngajatNavigation")
                        .WithMany("ContractAngajati")
                        .HasForeignKey("IdAngajat")
                        .HasConstraintName("fk__contracta__idang__398d8eee");

                    b.HasOne("Echipa_de_fotbal.Models.Echipa", "IdEchipaNavigation")
                        .WithMany("Contractangajati")
                        .HasForeignKey("IdEchipa")
                        .HasConstraintName("fk__contracta__idech__38996ab5");

                    b.Navigation("IdAngajatNavigation");

                    b.Navigation("IdEchipaNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.ContractJucator", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Echipa", "IdEchipaNavigation")
                        .WithMany("Contractjucatori")
                        .HasForeignKey("IdEchipa")
                        .HasConstraintName("fk__contractj__idech__4316f928");

                    b.HasOne("Echipa_de_fotbal.Models.Jucator", "IdJucatorNavigation")
                        .WithMany("Contractjucatori")
                        .HasForeignKey("IdJucator")
                        .HasConstraintName("fk__contractj__idjuc__440b1d61");

                    b.Navigation("IdEchipaNavigation");

                    b.Navigation("IdJucatorNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Echipa", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Campionat", "IdCampionatNavigation")
                        .WithMany("Echipe")
                        .HasForeignKey("IdCampionat")
                        .HasConstraintName("fk__echipa__idcampio__35bcfe0a");

                    b.HasOne("Echipa_de_fotbal.Models.Stadion", "IdStadionNavigation")
                        .WithMany("Echipe")
                        .HasForeignKey("IdStadion")
                        .HasConstraintName("fk__echipa__idstadio__36b12243");

                    b.Navigation("IdCampionatNavigation");

                    b.Navigation("IdStadionNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Jucator", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Echipa", "IdEchipaNavigation")
                        .WithMany("Jucatori")
                        .HasForeignKey("IdEchipa")
                        .HasConstraintName("fk__jucator__idechip__3a81b327");

                    b.Navigation("IdEchipaNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.SponsorEchipa", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Echipa", "IdEchipaNavigation")
                        .WithMany("SponsorEchipe")
                        .HasForeignKey("IdEchipa")
                        .IsRequired()
                        .HasConstraintName("fk__sponsorec__idech__46e78a0c");

                    b.HasOne("Echipa_de_fotbal.Models.Sponsor", "IdSponsorNavigation")
                        .WithMany("SponsorEchipe")
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("fk__sponsorec__idspo__44ff419a");

                    b.Navigation("IdEchipaNavigation");

                    b.Navigation("IdSponsorNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.SponsorJucator", b =>
                {
                    b.HasOne("Echipa_de_fotbal.Models.Jucator", "IdJucatorNavigation")
                        .WithMany("Sponsorjucatori")
                        .HasForeignKey("IdJucator")
                        .IsRequired()
                        .HasConstraintName("fk__sponsorju__idjuc__47dbae45");

                    b.HasOne("Echipa_de_fotbal.Models.Sponsor", "IdSponsorNavigation")
                        .WithMany("SponsorJucatori")
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("fk__sponsorju__idspo__45f365d3");

                    b.Navigation("IdJucatorNavigation");

                    b.Navigation("IdSponsorNavigation");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Angajat", b =>
                {
                    b.Navigation("ContractAngajati");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Campionat", b =>
                {
                    b.Navigation("Echipe");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Echipa", b =>
                {
                    b.Navigation("Angajati");

                    b.Navigation("Contractangajati");

                    b.Navigation("Contractjucatori");

                    b.Navigation("Jucatori");

                    b.Navigation("SponsorEchipe");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Jucator", b =>
                {
                    b.Navigation("Contractjucatori");

                    b.Navigation("Sponsorjucatori");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Sponsor", b =>
                {
                    b.Navigation("SponsorEchipe");

                    b.Navigation("SponsorJucatori");
                });

            modelBuilder.Entity("Echipa_de_fotbal.Models.Stadion", b =>
                {
                    b.Navigation("Echipe");
                });
#pragma warning restore 612, 618
        }
    }
}
